# Owner: mousamdas156@gmail.com
# ================================================================================
# FILE: db/models/tenantSettings.py — Tenant Settings Database Model
# ================================================================================
# Why this file is used:
#   - Houses SaaS tenant configuration profiles like currency, timezone, language, etc.
#
# What components are inside:
#   - TenantSettings (SQLAlchemy model class)
# ================================================================================
# Import uuid for UUID fields
import uuid
# Import Decimal for monetary representation
from decimal import Decimal

# Import column types and FK from SQLAlchemy
from sqlalchemy import (
    Boolean,
    ForeignKey,
    Integer,
    Numeric,
    String,
)
# Import Postgres-specific UUID column type
from sqlalchemy.dialects.postgresql import UUID
# Import ORM mappings and relationships
from sqlalchemy.orm import Mapped, mapped_column, relationship
# Import base model stub
from app.db.base import BaseModelWithUpdate


class TenantSettings(BaseModelWithUpdate):
    """
    TenantSettings database entity.
    Stores customizable configuration options specific to a single tenant.
    """
    __tablename__ = "tenant_settings"

    # Link to the parent Tenant details record (one settings profile per tenant)
    tenantId: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants_details.id", ondelete="CASCADE"),
        unique=True,
        nullable=False,
    )

    # Base billing / transaction currency (default to Indian Rupee 'INR')
    currency: Mapped[str] = mapped_column(String(10), default="INR", server_default="INR", nullable=False)
    # Default timezone context for booking, orders, and audits (default to 'Asia/Kolkata')
    timezone: Mapped[str] = mapped_column(String(50), default="Asia/Kolkata", server_default="Asia/Kolkata", nullable=False)
    # Default localized communication language (default to English 'en')
    language: Mapped[str] = mapped_column(String(10), default="en", server_default="en", nullable=False)
    # Unique customizable prefix prepended to invoices generated by the tenant
    invoicePrefix: Mapped[str | None] = mapped_column(String(50), nullable=True)
    # Numerical representation of the starting month of the fiscal year (default to 4, i.e., April)
    fiscalYearStart: Mapped[int] = mapped_column(Integer, default=4, server_default="4", nullable=False)
    # Default tax/GST percentage rate applied globally to products/services
    taxRate: Mapped[Decimal] = mapped_column(Numeric(5, 2), default=Decimal("0.00"), server_default="0.00", nullable=False)
    # Toggle switch to enable system email/SMS alerts to customers
    enableNotifications: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true", nullable=False)
    # Toggle switch to enable automatic renewal of the tenant subscription plan
    enableAutoRenew: Mapped[bool] = mapped_column(Boolean, default=True, server_default="true", nullable=False)

    # Database relationship linking back to the parent Tenant record
    tenant = relationship("Tenant", back_populates="settings")
