# Owner: mousamdas156@gmail.com
# ================================================================================
# FILE: db/base.py — SQLAlchemy Declarative Base & Reusable Base Models
# ================================================================================
# Why this file is used:
#   - Exposes base models and constraint templates inherited by every ORM table.
#
# What components are inside:
#   - convention         -> Named constraint mappings to ensure safe, consistent database migrations.
#   - Base               -> Core DeclarativeBase instance.
#   - BaseUUID           -> UUID identifier primary key model stub.
#   - BaseModelCreated   -> UUID identifier + creation timestamp model stub.
#   - BaseModelWithUpdate-> UUID identifier + creation + update timestamp model stub.
#   - BaseModel          -> Standard model stub: UUID, timestamps, and active flags.
# ================================================================================
"""
SQLAlchemy declarative base and reusable base model.

BaseModel provides common fields that every table should have:
  - id: UUID primary key (auto-generated)
  - created_at: Timestamp set on row creation
  - updated_at: Timestamp auto-updated on modification
  - is_active: Soft delete flag

Naming conventions ensure consistent, predictable constraint names
across all migrations (avoids autogenerated names that vary per platform).
"""

import uuid
from datetime import datetime

from sqlalchemy import Boolean, DateTime, MetaData
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column
from sqlalchemy.sql import func

# ──────────────────────────────────────────────
# Naming conventions for constraints & indexes
# ──────────────────────────────────────────────

convention = {
    "ix": "ix_%(column_0_label)s",
    "uq": "uq_%(table_name)s_%(column_0_name)s",
    "ck": "ck_%(table_name)s_%(constraint_name)s",
    "fk": "fk_%(table_name)s_%(column_0_name)s_%(referred_table_name)s",
    "pk": "pk_%(table_name)s",
}


class Base(DeclarativeBase):
    """
    Declarative base with naming conventions.

    All ORM models must inherit from this class (directly or via BaseModel).
    """

    metadata = MetaData(naming_convention=convention)


class BaseUUID(Base):
    """Base with UUID PK only (no timestamps)."""

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )


class BaseModelCreated(BaseUUID):
    """Base with UUID PK + createdAt."""

    __abstract__ = True

    createdAt: Mapped[datetime] = mapped_column(
        "created_at",
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class BaseModelWithUpdate(BaseModelCreated):
    """Base with UUID PK + createdAt + updatedAt."""

    __abstract__ = True

    updatedAt: Mapped[datetime] = mapped_column(
        "updated_at",
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class BaseModel(Base):
    """
    Abstract base model with common fields.

    Inherit from this class to get id, createdAt, updatedAt, and isActive
    columns automatically:

        class User(BaseModel):
            __tablename__ = "users"
            email: Mapped[str] = mapped_column(unique=True)
    """

    __abstract__ = True

    id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        primary_key=True,
        default=uuid.uuid4,
    )
    createdAt: Mapped[datetime] = mapped_column(
        "created_at",
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )
    updatedAt: Mapped[datetime] = mapped_column(
        "updated_at",
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )
    isActive: Mapped[bool] = mapped_column(
        "is_active",
        Boolean,
        default=True,
        nullable=False,
    )