"""merge github repository

Revision ID: 37d916d07c54
Revises: df84845c699e
Create Date: 2026-07-11 17:49:40.418377

This revision originally contained an autogenerated duplicate of the
core schema already created by df84845c699e. It is intentionally kept
as a no-op so existing Alembic revision history remains valid.
"""

from typing import Sequence, Union

from alembic import op


revision: str = "37d916d07c54"
down_revision: Union[str, None] = "df84845c699e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    pass


def downgrade() -> None:
    pass
