"""integrate all modules

Revision ID: df84845c699e
Revises: 
Create Date: 2026-07-10 00:05:20.215101

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'df84845c699e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('approvalRequests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=20), nullable=False),
    sa.Column('submitted_version_number', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('submitted_by', sa.UUID(), nullable=False),
    sa.Column('submitted_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('remarks', sa.String(length=1000), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_approvalRequests_ck_approvalRequests_approval_status')),
    sa.CheckConstraint("entity_type IN ('STORE','SECTION','PRODUCT','SERVICE','BLOG','CATEGORY','OFFER','POLICY','FORM','MEDIA','BRAND')", name=op.f('ck_approvalRequests_ck_approvalRequests_entity_type')),
    sa.CheckConstraint("operation_type IN ('CREATE','UPDATE','DELETE')", name=op.f('ck_approvalRequests_ck_approvalRequests_operation_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approvalRequests'))
    )
    op.create_index(op.f('ix_approvalRequests_approval_status'), 'approvalRequests', ['approval_status'], unique=False)
    op.create_index(op.f('ix_approvalRequests_entity_id'), 'approvalRequests', ['entity_id'], unique=False)
    op.create_index(op.f('ix_approvalRequests_entity_type'), 'approvalRequests', ['entity_type'], unique=False)
    op.create_index(op.f('ix_approvalRequests_submitted_at'), 'approvalRequests', ['submitted_at'], unique=False)
    op.create_index(op.f('ix_approvalRequests_tenant_id'), 'approvalRequests', ['tenant_id'], unique=False)
    op.create_table('auditLogs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('changed_fields', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('performed_by', sa.UUID(), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("action_type IN ('CREATE','UPDATE','DELETE','RESTORE','LOGIN','LOGOUT','APPROVE','REJECT','PAYMENT','REFUND','CANCEL','RETURN')", name=op.f('ck_auditLogs_ck_auditLogs_action_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_auditLogs'))
    )
    op.create_index(op.f('ix_auditLogs_created_at'), 'auditLogs', ['created_at'], unique=False)
    op.create_index(op.f('ix_auditLogs_entity_id'), 'auditLogs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_auditLogs_entity_type'), 'auditLogs', ['entity_type'], unique=False)
    op.create_index(op.f('ix_auditLogs_performed_by'), 'auditLogs', ['performed_by'], unique=False)
    op.create_table('brands',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('owner_store_id', sa.UUID(), nullable=True),
    sa.Column('brand_name', sa.String(length=150), nullable=False),
    sa.Column('brand_slug', sa.String(length=180), nullable=False),
    sa.Column('logo_media_id', sa.UUID(), nullable=True),
    sa.Column('website_url', sa.String(length=500), nullable=True),
    sa.Column('support_email', sa.String(length=255), nullable=True),
    sa.Column('support_mobile', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('country_of_origin', sa.String(length=100), nullable=True),
    sa.Column('gst_number', sa.String(length=15), nullable=True),
    sa.Column('trademark_number', sa.String(length=100), nullable=True),
    sa.Column('trademark_document_media_id', sa.UUID(), nullable=True),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_platform_brand', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("verification_status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_brands_ck_brands_verification_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brands')),
    sa.UniqueConstraint('brand_slug', name='uq_brands_brand_slug'),
    sa.UniqueConstraint('owner_store_id', 'brand_name', name='uq_brands_owner_store_brand_name')
    )
    op.create_index(op.f('ix_brands_brand_name'), 'brands', ['brand_name'], unique=False)
    op.create_index(op.f('ix_brands_is_active'), 'brands', ['is_active'], unique=False)
    op.create_index(op.f('ix_brands_is_platform_brand'), 'brands', ['is_platform_brand'], unique=False)
    op.create_index(op.f('ix_brands_owner_store_id'), 'brands', ['owner_store_id'], unique=False)
    op.create_index(op.f('ix_brands_tenant_id'), 'brands', ['tenant_id'], unique=False)
    op.create_table('categories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('parent_category_id', sa.UUID(), nullable=True),
    sa.Column('category_type', sa.String(length=20), nullable=False),
    sa.Column('category_name', sa.String(length=150), nullable=False),
    sa.Column('category_slug', sa.String(length=180), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=True),
    sa.Column('long_description', sa.Text(), nullable=True),
    sa.Column('image_media_id', sa.UUID(), nullable=True),
    sa.Column('icon_media_id', sa.UUID(), nullable=True),
    sa.Column('display_order', sa.SmallInteger(), nullable=False),
    sa.Column('level_number', sa.SmallInteger(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('is_system_category', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('approved_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_categories_ck_categories_approval_status')),
    sa.CheckConstraint("category_type IN ('PRODUCT', 'SERVICE', 'BOTH')", name=op.f('ck_categories_ck_categories_category_type')),
    sa.ForeignKeyConstraint(['parent_category_id'], ['categories.id'], name=op.f('fk_categories_parent_category_id_categories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('store_id', 'category_name', name='uq_categories_store_name'),
    sa.UniqueConstraint('store_id', 'category_slug', name='uq_categories_store_slug')
    )
    op.create_index('idx_categories_category_type', 'categories', ['category_type'], unique=False)
    op.create_index('idx_categories_is_active', 'categories', ['is_active'], unique=False)
    op.create_index('idx_categories_parent_id', 'categories', ['parent_category_id'], unique=False)
    op.create_index('idx_categories_store_id', 'categories', ['store_id'], unique=False)
    op.create_index('idx_categories_tenant_id', 'categories', ['tenant_id'], unique=False)
    op.create_index('uq_categories_platform_name', 'categories', ['category_name'], unique=True, postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.create_index('uq_categories_platform_slug', 'categories', ['category_slug'], unique=True, postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.create_table('chatUsers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_chatUsers')),
    sa.UniqueConstraint('email', name=op.f('uq_chatUsers_email')),
    sa.UniqueConstraint('store_id', name=op.f('uq_chatUsers_store_id'))
    )
    op.create_table('conversations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_type', sa.String(length=30), nullable=False),
    sa.Column('store_id', sa.Integer(), nullable=True),
    sa.Column('participant_1', sa.Integer(), nullable=False),
    sa.Column('participant_2', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_conversations'))
    )
    op.create_table('customer_groups',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_groups')),
    sa.UniqueConstraint('store_id', 'group_name', name='uq_groups_store_name')
    )
    op.create_table('customers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_code', sa.String(length=30), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_guest_customer', sa.Boolean(), nullable=True),
    sa.Column('is_email_verified', sa.Boolean(), nullable=True),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=True),
    sa.Column('last_login_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('registered_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("status IN ('ACTIVE','INACTIVE','BLOCKED')", name=op.f('ck_customers_ck_customers_status')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customers')),
    sa.UniqueConstraint('customer_code', name=op.f('uq_customers_customer_code')),
    sa.UniqueConstraint('store_id', 'email', name='uq_customers_store_email'),
    sa.UniqueConstraint('store_id', 'mobile', name='uq_customers_store_mobile')
    )
    op.create_table('entity_verifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('verification_type', sa.String(length=30), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('verified_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("entity_type IN ('CUSTOMER','ORDER','BOOKING')", name=op.f('ck_entity_verifications_ck_entity_type')),
    sa.CheckConstraint("verification_type IN ('EMAIL','MOBILE','ORDER_CONFIRMATION','BOOKING_CONFIRMATION')", name=op.f('ck_entity_verifications_ck_verification_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entity_verifications'))
    )
    op.create_table('entityVersions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('version_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("entity_type IN ('STORE','SECTION','PRODUCT','SERVICE','BLOG','CATEGORY','OFFER','POLICY','FORM','MEDIA','BRAND')", name=op.f('ck_entityVersions_ck_entityVersions_entity_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entityVersions')),
    sa.UniqueConstraint('entity_type', 'entity_id', 'version_number', name='uq_entity_version_number')
    )
    op.create_index(op.f('ix_entityVersions_created_at'), 'entityVersions', ['created_at'], unique=False)
    op.create_index(op.f('ix_entityVersions_entity_id'), 'entityVersions', ['entity_id'], unique=False)
    op.create_index(op.f('ix_entityVersions_entity_type'), 'entityVersions', ['entity_type'], unique=False)
    op.create_table('permissions',
    sa.Column('permission_name', sa.String(length=150), nullable=False),
    sa.Column('permission_code', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('permission_code', name=op.f('uq_permissions_permission_code')),
    sa.UniqueConstraint('permission_name', name=op.f('uq_permissions_permission_name'))
    )
    op.create_table('roles',
    sa.Column('role_name', sa.String(length=100), nullable=False),
    sa.Column('role_code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_system_role', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('role_code', name=op.f('uq_roles_role_code'))
    )
    op.create_table('statusHistory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=False),
    sa.Column('change_reason', sa.String(length=500), nullable=True),
    sa.Column('changed_by', sa.UUID(), nullable=False),
    sa.Column('changed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("entity_type IN ('PRODUCT','SERVICE','ORDER','BOOKING','CUSTOMER','SHIPMENT','OFFER','STORE','BRAND','CATEGORY')", name=op.f('ck_statusHistory_ck_statusHistory_entity_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_statusHistory'))
    )
    op.create_index(op.f('ix_statusHistory_changed_at'), 'statusHistory', ['changed_at'], unique=False)
    op.create_index(op.f('ix_statusHistory_entity_id'), 'statusHistory', ['entity_id'], unique=False)
    op.create_index(op.f('ix_statusHistory_entity_type'), 'statusHistory', ['entity_type'], unique=False)
    op.create_table('subscription_plans',
    sa.Column('planCode', sa.String(length=50), nullable=False),
    sa.Column('planName', sa.String(length=100), nullable=False),
    sa.Column('monthlyPrice', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('transactionCommissionPercent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"monthlyPrice" >= 0', name=op.f('ck_subscription_plans_ck_monthly_price_positive')),
    sa.CheckConstraint('"transactionCommissionPercent" >= 0 AND "transactionCommissionPercent" <= 100', name=op.f('ck_subscription_plans_ck_transaction_commission_percent')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscription_plans')),
    sa.UniqueConstraint('planCode', name=op.f('uq_subscription_plans_planCode'))
    )
    op.create_table('tags',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('store_id', sa.UUID(), nullable=True),
    sa.Column('tag_name', sa.String(length=100), nullable=False),
    sa.Column('tag_slug', sa.String(length=120), nullable=False),
    sa.Column('tag_type', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('color_code', sa.String(length=7), nullable=True),
    sa.Column('is_system_tag', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True),
    sa.CheckConstraint("color_code IS NULL OR color_code ~ '^#[0-9A-Fa-f]{6}$'", name=op.f('ck_tags_ck_tags_color_code')),
    sa.CheckConstraint("tag_type IN ('PRODUCT', 'SERVICE', 'CUSTOMER', 'ORDER', 'BOOKING', 'BLOG', 'OFFER', 'CATEGORY', 'BRAND', 'GENERAL')", name=op.f('ck_tags_ck_tags_tag_type')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tags')),
    sa.UniqueConstraint('store_id', 'tag_type', 'tag_name', name='uq_tags_store_name'),
    sa.UniqueConstraint('store_id', 'tag_type', 'tag_slug', name='uq_tags_store_slug')
    )
    op.create_index('idx_tags_is_active', 'tags', ['is_active'], unique=False)
    op.create_index('idx_tags_is_system_tag', 'tags', ['is_system_tag'], unique=False)
    op.create_index('idx_tags_store_id', 'tags', ['store_id'], unique=False)
    op.create_index('idx_tags_tag_type', 'tags', ['tag_type'], unique=False)
    op.create_index('idx_tags_tenant_id', 'tags', ['tenant_id'], unique=False)
    op.create_index('uq_tags_platform_name', 'tags', ['tag_type', 'tag_name'], unique=True, postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.create_index('uq_tags_platform_slug', 'tags', ['tag_type', 'tag_slug'], unique=True, postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.create_table('tenantStatus',
    sa.Column('id', sa.SmallInteger(), autoincrement=True, nullable=False),
    sa.Column('statusName', sa.String(length=50), nullable=False),
    sa.Column('statusDescription', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenantStatus')),
    sa.UniqueConstraint('statusName', name=op.f('uq_tenantStatus_statusName'))
    )
    op.create_table('tenants_details',
    sa.Column('gstNumber', sa.String(length=15), nullable=True),
    sa.Column('panNumber', sa.String(length=10), nullable=False),
    sa.Column('documentMediaLink', sa.Text(), nullable=True),
    sa.Column('documentVerificationDone', sa.Boolean(), nullable=False),
    sa.Column('documentVerificationDoneBy', sa.UUID(), nullable=True),
    sa.Column('documentVerificationDoneAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('businessName', sa.String(length=255), nullable=False),
    sa.Column('legalName', sa.String(length=255), nullable=False),
    sa.Column('logoMediaId', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('whatsappMobile', sa.String(length=15), nullable=True),
    sa.Column('ownerName', sa.String(length=150), nullable=False),
    sa.Column('businessAddressLine1', sa.String(length=255), nullable=False),
    sa.Column('businessAddressLine2', sa.String(length=255), nullable=True),
    sa.Column('locationLatitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('locationLongitude', sa.Numeric(precision=10, scale=7), nullable=True),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('postOffice', sa.String(length=100), nullable=True),
    sa.Column('policeStation', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), server_default='India', nullable=False),
    sa.Column('postalCode', sa.String(length=10), nullable=False),
    sa.Column('businessType', sa.String(length=100), nullable=False),
    sa.Column('businessDescription', sa.Text(), nullable=True),
    sa.Column('employeeCount', sa.Integer(), nullable=True),
    sa.Column('registeredAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('"employeeCount" >= 0', name=op.f('ck_tenants_details_ck_employee_count_positive')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenants_details')),
    sa.UniqueConstraint('email', name=op.f('uq_tenants_details_email')),
    sa.UniqueConstraint('gstNumber', name=op.f('uq_tenants_details_gstNumber')),
    sa.UniqueConstraint('mobile', name=op.f('uq_tenants_details_mobile')),
    sa.UniqueConstraint('panNumber', name=op.f('uq_tenants_details_panNumber'))
    )
    op.create_index('idx_tenant_city_state', 'tenants_details', ['city', 'state'], unique=False)
    op.create_table('users',
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('whatsapp_mobile', sa.String(length=15), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_email_verified', sa.Boolean(), nullable=False),
    sa.Column('is_mobile_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email')),
    sa.UniqueConstraint('mobile', name=op.f('uq_users_mobile'))
    )
    op.create_table('approval_request_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('approval_request_id', sa.UUID(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('review_comment', sa.String(length=2000), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("approval_status IN ('PENDING','APPROVED','REJECTED')", name=op.f('ck_approval_request_versions_ck_approval_request_versions_approval_status')),
    sa.ForeignKeyConstraint(['approval_request_id'], ['approvalRequests.id'], name=op.f('fk_approval_request_versions_approval_request_id_approvalRequests')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_approval_request_versions')),
    sa.UniqueConstraint('approval_request_id', 'version_number', name='uq_approval_request_version')
    )
    op.create_table('brandApprovals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('brand_id', sa.UUID(), nullable=False),
    sa.Column('requesting_store_id', sa.UUID(), nullable=False),
    sa.Column('brand_owner_store_id', sa.UUID(), nullable=False),
    sa.Column('request_status', sa.String(length=20), nullable=False),
    sa.Column('request_message', sa.String(length=1000), nullable=True),
    sa.Column('supporting_document_media_id', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('rejection_reason', sa.String(length=1000), nullable=True),
    sa.Column('approval_start_date', sa.Date(), nullable=True),
    sa.Column('approval_end_date', sa.Date(), nullable=True),
    sa.Column('revoked_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('revoked_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("request_status IN ('PENDING', 'APPROVED', 'REJECTED', 'REVOKED', 'EXPIRED')", name=op.f('ck_brandApprovals_ck_brandApprovals_request_status')),
    sa.CheckConstraint('approval_end_date IS NULL OR approval_start_date <= approval_end_date', name=op.f('ck_brandApprovals_ck_brandApprovals_date_range')),
    sa.CheckConstraint('requesting_store_id <> brand_owner_store_id', name=op.f('ck_brandApprovals_ck_brandApprovals_different_stores')),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], name=op.f('fk_brandApprovals_brand_id_brands')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_brandApprovals')),
    sa.UniqueConstraint('brand_id', 'requesting_store_id', name='uq_brandApprovals_brand_requesting_store')
    )
    op.create_index(op.f('ix_brandApprovals_approval_end_date'), 'brandApprovals', ['approval_end_date'], unique=False)
    op.create_index(op.f('ix_brandApprovals_brand_id'), 'brandApprovals', ['brand_id'], unique=False)
    op.create_index(op.f('ix_brandApprovals_brand_owner_store_id'), 'brandApprovals', ['brand_owner_store_id'], unique=False)
    op.create_index(op.f('ix_brandApprovals_request_status'), 'brandApprovals', ['request_status'], unique=False)
    op.create_index(op.f('ix_brandApprovals_requesting_store_id'), 'brandApprovals', ['requesting_store_id'], unique=False)
    op.create_table('customer_activity_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=True),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('activity_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_activity_logs_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_activity_logs'))
    )
    op.create_table('customerAddresses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('address_type', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('mobile', sa.String(length=15), nullable=False),
    sa.Column('address_line_1', sa.String(length=255), nullable=False),
    sa.Column('address_line_2', sa.String(length=255), nullable=True),
    sa.Column('landmark', sa.String(length=150), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('postal_code', sa.String(length=10), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.CheckConstraint("address_type IN ('SHIPPING','BILLING')", name=op.f('ck_customerAddresses_ck_address_type')),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customerAddresses_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customerAddresses'))
    )
    op.create_table('customer_consent_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('consent_type', sa.String(length=50), nullable=False),
    sa.Column('accepted', sa.Boolean(), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('accepted_at', sa.TIMESTAMP(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_consent_logs_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_consent_logs'))
    )
    op.create_table('customer_group_members',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('group_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_group_members_customer_id_customers')),
    sa.ForeignKeyConstraint(['group_id'], ['customer_groups.id'], name=op.f('fk_customer_group_members_group_id_customer_groups')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_group_members')),
    sa.UniqueConstraint('customer_id', 'group_id', name='uq_group_member')
    )
    op.create_table('customer_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('note_text', sa.Text(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_notes_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_notes'))
    )
    op.create_table('customer_password_reset_tokens',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('used_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customer_password_reset_tokens_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customer_password_reset_tokens'))
    )
    op.create_table('customerSessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.String(length=1000), nullable=True),
    sa.Column('login_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('logout_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('expires_at', sa.TIMESTAMP(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_customerSessions_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_customerSessions'))
    )
    op.create_table('guest_checkout_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('customer_id', sa.UUID(), nullable=True),
    sa.Column('order_id', sa.UUID(), nullable=True),
    sa.Column('booking_id', sa.UUID(), nullable=True),
    sa.Column('guest_name', sa.String(length=150), nullable=False),
    sa.Column('guest_email', sa.String(length=255), nullable=False),
    sa.Column('guest_mobile', sa.String(length=15), nullable=False),
    sa.Column('guest_address_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('converted_to_customer', sa.Boolean(), nullable=True),
    sa.Column('converted_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], name=op.f('fk_guest_checkout_logs_customer_id_customers')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guest_checkout_logs'))
    )
    op.create_table('loginHistory',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('login_status', sa.String(length=20), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("login_status IN ('SUCCESS', 'FAILED')", name=op.f('ck_loginHistory_ck_login_status')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_loginHistory_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_loginHistory'))
    )
    op.create_table('media_files',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('folder_name', sa.String(length=100), nullable=True),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('original_file_name', sa.String(length=255), nullable=False),
    sa.Column('file_extension', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_provider', sa.String(length=50), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=False),
    sa.Column('checksum_hash', sa.String(length=128), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('approval_status_change_by', sa.UUID(), nullable=True),
    sa.Column('approval_status_change_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('uploaded_by', sa.UUID(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_media_files_ck_media_files_approval_status')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants_details.id'], name=op.f('fk_media_files_tenant_id_tenants_details')),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_media_files_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_files')),
    sa.UniqueConstraint('checksum_hash', name=op.f('uq_media_files_checksum_hash'))
    )
    op.create_index('idx_media_files_created_at', 'media_files', ['created_at'], unique=False)
    op.create_index('idx_media_files_tenant_id', 'media_files', ['tenant_id'], unique=False)
    op.create_index('idx_media_files_uploaded_by', 'media_files', ['uploaded_by'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('conversation_id', sa.Integer(), nullable=False),
    sa.Column('sender_id', sa.Integer(), nullable=False),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=20), nullable=False),
    sa.Column('file_url', sa.String(length=500), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['conversation_id'], ['conversations.id'], name=op.f('fk_messages_conversation_id_conversations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_messages'))
    )
    op.create_table('otpVerifications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('purpose', sa.String(length=50), nullable=False),
    sa.Column('otp_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('attempts', sa.SmallInteger(), nullable=False),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("purpose IN ('LOGIN', 'SIGNUP', 'RESET', 'TRANSACTION')", name=op.f('ck_otpVerifications_ck_otp_purpose')),
    sa.CheckConstraint('attempts <= 5', name=op.f('ck_otpVerifications_ck_otp_attempts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_otpVerifications_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otpVerifications'))
    )
    op.create_table('passwordResetTokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_passwordResetTokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_passwordResetTokens'))
    )
    op.create_table('plan_features',
    sa.Column('planId', sa.UUID(), nullable=False),
    sa.Column('featureName', sa.String(length=100), nullable=False),
    sa.Column('featureCode', sa.String(length=50), nullable=False),
    sa.Column('featureValue', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['subscription_plans.id'], name=op.f('fk_plan_features_planId_subscription_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_plan_features')),
    sa.UniqueConstraint('planId', 'featureCode', name='uq_plan_feature_code')
    )
    op.create_table('refreshTokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('device_name', sa.String(length=100), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('createdAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_refreshTokens_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_refreshTokens'))
    )
    op.create_table('rolePermissionMapping',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_rolePermissionMapping_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_rolePermissionMapping_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rolePermissionMapping')),
    sa.UniqueConstraint('role_id', 'permission_id', name='uq_role_permission')
    )
    op.create_table('seo_metadata',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=50), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('meta_title', sa.String(length=255), nullable=True),
    sa.Column('meta_description', sa.String(length=500), nullable=True),
    sa.Column('canonical_url', sa.String(length=1000), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('robots_index', sa.Boolean(), nullable=False),
    sa.Column('robots_follow', sa.Boolean(), nullable=False),
    sa.Column('seo_score', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("entity_type IN ('STORE', 'PRODUCT', 'SERVICE', 'BLOG', 'CATEGORY', 'OFFER', 'POLICY', 'FORM')", name=op.f('ck_seo_metadata_ck_seo_metadata_entity_type')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants_details.id'], name=op.f('fk_seo_metadata_tenant_id_tenants_details')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seo_metadata')),
    sa.UniqueConstraint('entity_type', 'entity_id', name='uq_seo_metadata_entity_type_entity_id'),
    sa.UniqueConstraint('entity_type', 'slug', name='uq_seo_metadata_entity_type_slug')
    )
    op.create_table('store_staff_permissions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.Column('granted_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['granted_by'], ['users.id'], name=op.f('fk_store_staff_permissions_granted_by_users')),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_store_staff_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_store_staff_permissions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_staff_permissions')),
    sa.UniqueConstraint('user_id', 'store_id', 'permission_id', name='uq_user_store_permission')
    )
    op.create_table('tagMappings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(length=30), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('mapped_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.CheckConstraint("entity_type IN ('PRODUCT', 'SERVICE', 'CUSTOMER', 'ORDER', 'BOOKING', 'BLOG', 'OFFER', 'CATEGORY', 'BRAND')", name=op.f('ck_tagMappings_ck_tagMappings_entity_type')),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name=op.f('fk_tagMappings_tag_id_tags')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tagMappings')),
    sa.UniqueConstraint('tag_id', 'entity_type', 'entity_id', name='uq_tagMappings_prevent_duplicate')
    )
    op.create_index('idx_tagMappings_created_at', 'tagMappings', ['created_at'], unique=False)
    op.create_index('idx_tagMappings_entity_id', 'tagMappings', ['entity_id'], unique=False)
    op.create_index('idx_tagMappings_entity_type', 'tagMappings', ['entity_type'], unique=False)
    op.create_index('idx_tagMappings_mapped_by', 'tagMappings', ['mapped_by'], unique=False)
    op.create_index('idx_tagMappings_tag_id', 'tagMappings', ['tag_id'], unique=False)
    op.create_table('tenantDomainMapping',
    sa.Column('tenantId', sa.UUID(), nullable=False),
    sa.Column('domainType', sa.String(length=20), nullable=False),
    sa.Column('subDomain', sa.String(length=100), nullable=True),
    sa.Column('customDomain', sa.String(length=255), nullable=True),
    sa.Column('isPrimary', sa.Boolean(), nullable=False),
    sa.Column('sslExpiry', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint('("subDomain" IS NOT NULL) OR ("customDomain" IS NOT NULL)', name=op.f('ck_tenantDomainMapping_ck_domain_required')),
    sa.ForeignKeyConstraint(['tenantId'], ['tenants_details.id'], name=op.f('fk_tenantDomainMapping_tenantId_tenants_details'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenantDomainMapping')),
    sa.UniqueConstraint('customDomain', name=op.f('uq_tenantDomainMapping_customDomain')),
    sa.UniqueConstraint('subDomain', name=op.f('uq_tenantDomainMapping_subDomain'))
    )
    op.create_table('tenantPlanHistory',
    sa.Column('tenantId', sa.UUID(), nullable=False),
    sa.Column('oldPlanId', sa.UUID(), nullable=True),
    sa.Column('newPlanId', sa.UUID(), nullable=True),
    sa.Column('changedBy', sa.UUID(), nullable=False),
    sa.Column('changeReason', sa.String(length=255), nullable=True),
    sa.Column('changedAt', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['newPlanId'], ['subscription_plans.id'], name=op.f('fk_tenantPlanHistory_newPlanId_subscription_plans')),
    sa.ForeignKeyConstraint(['oldPlanId'], ['subscription_plans.id'], name=op.f('fk_tenantPlanHistory_oldPlanId_subscription_plans')),
    sa.ForeignKeyConstraint(['tenantId'], ['tenants_details.id'], name=op.f('fk_tenantPlanHistory_tenantId_tenants_details'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenantPlanHistory'))
    )
    op.create_table('tenantPlanMapping',
    sa.Column('tenantId', sa.UUID(), nullable=False),
    sa.Column('planId', sa.UUID(), nullable=False),
    sa.Column('planStartDate', sa.Date(), nullable=False),
    sa.Column('planEndDate', sa.Date(), nullable=True),
    sa.Column('planUpdateAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('autoRenew', sa.Boolean(), nullable=False),
    sa.Column('planChange', sa.Boolean(), nullable=False),
    sa.Column('changeReason', sa.String(length=255), nullable=True),
    sa.Column('statusId', sa.SmallInteger(), nullable=False),
    sa.Column('statusUpdateAt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('statusUpdateBy', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['planId'], ['subscription_plans.id'], name=op.f('fk_tenantPlanMapping_planId_subscription_plans')),
    sa.ForeignKeyConstraint(['statusId'], ['tenantStatus.id'], name=op.f('fk_tenantPlanMapping_statusId_tenantStatus')),
    sa.ForeignKeyConstraint(['tenantId'], ['tenants_details.id'], name=op.f('fk_tenantPlanMapping_tenantId_tenants_details'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_tenantPlanMapping')),
    sa.UniqueConstraint('tenantId', name='uq_tenant_active_plan')
    )
    op.create_table('userRoleMapping',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=True),
    sa.Column('assigned_by', sa.UUID(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by'], ['users.id'], name=op.f('fk_userRoleMapping_assigned_by_users')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_userRoleMapping_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants_details.id'], name=op.f('fk_userRoleMapping_tenant_id_tenants_details')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userRoleMapping_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userRoleMapping')),
    sa.UniqueConstraint('user_id', 'role_id', 'tenant_id', name='uq_user_role_tenant')
    )
    op.create_table('userSecuritySettings',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('two_factor_enabled', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.SmallInteger(), nullable=False),
    sa.Column('account_locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_changed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userSecuritySettings_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userSecuritySettings')),
    sa.UniqueConstraint('user_id', name=op.f('uq_userSecuritySettings_user_id'))
    )
    op.create_table('media_metadata',
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('alt_text', sa.String(length=255), nullable=True),
    sa.Column('caption', sa.String(length=500), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('slug', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_media_metadata_media_file_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_metadata')),
    sa.UniqueConstraint('media_file_id', name=op.f('uq_media_metadata_media_file_id'))
    )
    op.create_table('media_upload_logs',
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('action_type', sa.String(length=50), nullable=False),
    sa.Column('performed_by', sa.UUID(), nullable=False),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("action_type IN ('UPLOAD', 'UPDATE', 'DELETE', 'RESTORE', 'METADATA_UPDATE')", name=op.f('ck_media_upload_logs_ck_media_upload_logs_action_type')),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_media_upload_logs_media_file_id_media_files')),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], name=op.f('fk_media_upload_logs_performed_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_upload_logs'))
    )
    op.create_table('media_variants',
    sa.Column('media_file_id', sa.UUID(), nullable=False),
    sa.Column('variant_name', sa.String(length=50), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('public_url', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['media_file_id'], ['media_files.id'], name=op.f('fk_media_variants_media_file_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_media_variants')),
    sa.UniqueConstraint('media_file_id', 'variant_name', name='uq_media_variants_media_file_id_variant_name')
    )
    op.create_table('social_platforms',
    sa.Column('platform_code', sa.String(length=50), nullable=False),
    sa.Column('platform_name', sa.String(length=100), nullable=False),
    sa.Column('base_url', sa.String(length=255), nullable=True),
    sa.Column('icon_media_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['icon_media_id'], ['media_files.id'], name=op.f('fk_social_platforms_icon_media_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_platforms')),
    sa.UniqueConstraint('platform_code', name=op.f('uq_social_platforms_platform_code'))
    )
    op.create_table('stores',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=150), nullable=False),
    sa.Column('store_slug', sa.String(length=100), nullable=False),
    sa.Column('tagline', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('mobile', sa.String(length=15), nullable=True),
    sa.Column('whatsapp_mobile', sa.String(length=15), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_media_id', sa.UUID(), nullable=True),
    sa.Column('favicon_media_id', sa.UUID(), nullable=True),
    sa.Column('hero_media_id', sa.UUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('approval_status', sa.String(length=20), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("approval_status IN ('PENDING', 'APPROVED', 'REJECTED')", name=op.f('ck_stores_ck_stores_approval_status')),
    sa.ForeignKeyConstraint(['favicon_media_id'], ['media_files.id'], name=op.f('fk_stores_favicon_media_id_media_files')),
    sa.ForeignKeyConstraint(['hero_media_id'], ['media_files.id'], name=op.f('fk_stores_hero_media_id_media_files')),
    sa.ForeignKeyConstraint(['logo_media_id'], ['media_files.id'], name=op.f('fk_stores_logo_media_id_media_files')),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants_details.id'], name=op.f('fk_stores_tenant_id_tenants_details')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_stores')),
    sa.UniqueConstraint('store_slug', name=op.f('uq_stores_store_slug'))
    )
    op.create_table('userSessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_id', sa.UUID(), nullable=False),
    sa.Column('login_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('logout_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['refresh_token_id'], ['refreshTokens.id'], name=op.f('fk_userSessions_refresh_token_id_refreshTokens'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_userSessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_userSessions'))
    )
    op.create_table('website_themes',
    sa.Column('theme_name', sa.String(length=100), nullable=False),
    sa.Column('theme_code', sa.String(length=50), nullable=False),
    sa.Column('preview_image_id', sa.UUID(), nullable=True),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['preview_image_id'], ['media_files.id'], name=op.f('fk_website_themes_preview_image_id_media_files')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_website_themes')),
    sa.UniqueConstraint('theme_code', name=op.f('uq_website_themes_theme_code'))
    )
    op.create_table('sections',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('section_code', sa.String(length=50), nullable=False),
    sa.Column('section_name', sa.String(length=100), nullable=False),
    sa.Column('section_type', sa.String(length=50), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('config_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("section_type IN ('HERO', 'ABOUT', 'USP', 'PRODUCTS', 'SERVICES', 'BLOGS', 'CONTACT')", name=op.f('ck_sections_ck_sections_section_type')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_sections_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sections')),
    sa.UniqueConstraint('store_id', 'section_code', name='uq_sections_store_section_code'),
    sa.UniqueConstraint('store_id', 'sort_order', name='uq_sections_store_sort_order')
    )
    op.create_table('social_links',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('platform_id', sa.UUID(), nullable=False),
    sa.Column('profile_url', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['social_platforms.id'], name=op.f('fk_social_links_platform_id_social_platforms')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_social_links_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_social_links')),
    sa.UniqueConstraint('store_id', 'platform_id', name='uq_social_links_store_platform')
    )
    op.create_table('store_bank_accounts',
    sa.Column('store_id', sa.UUID(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=150), nullable=False),
    sa.Column('bank_name', sa.String(length=150), nullable=False),
    sa.Column('branch_name', sa.String(length=150), nullable=True),
    sa.Column('account_number_masked', sa.String(length=20), nullable=False),
    sa.Column('ifsc_code', sa.String(length=11), nullable=False),
    sa.Column('account_type', sa.String(length=30), nullable=False),
    sa.Column('verification_status', sa.String(length=20), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.CheckConstraint("account_type IN ('SAVINGS', 'CURRENT')", name=op.f('ck_store_bank_accounts_ck_bank_account_type')),
    sa.CheckConstraint("verification_status IN ('PENDING', 'VERIFIED', 'REJECTED')", name=op.f('ck_store_bank_accounts_ck_bank_verification_status')),
    sa.ForeignKeyConstraint(['store_id'], ['stores.id'], name=op.f('fk_store_bank_accounts_store_id_stores')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_store_bank_accounts'))
    )
    op.create_index('uq_store_bank_accounts_primary', 'store_bank_accounts', ['store_id'], unique=True, postgresql_where=sa.text('is_primary = TRUE'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_store_bank_accounts_primary', table_name='store_bank_accounts', postgresql_where=sa.text('is_primary = TRUE'))
    op.drop_table('store_bank_accounts')
    op.drop_table('social_links')
    op.drop_table('sections')
    op.drop_table('website_themes')
    op.drop_table('userSessions')
    op.drop_table('stores')
    op.drop_table('social_platforms')
    op.drop_table('media_variants')
    op.drop_table('media_upload_logs')
    op.drop_table('media_metadata')
    op.drop_table('userSecuritySettings')
    op.drop_table('userRoleMapping')
    op.drop_table('tenantPlanMapping')
    op.drop_table('tenantPlanHistory')
    op.drop_table('tenantDomainMapping')
    op.drop_index('idx_tagMappings_tag_id', table_name='tagMappings')
    op.drop_index('idx_tagMappings_mapped_by', table_name='tagMappings')
    op.drop_index('idx_tagMappings_entity_type', table_name='tagMappings')
    op.drop_index('idx_tagMappings_entity_id', table_name='tagMappings')
    op.drop_index('idx_tagMappings_created_at', table_name='tagMappings')
    op.drop_table('tagMappings')
    op.drop_table('store_staff_permissions')
    op.drop_table('seo_metadata')
    op.drop_table('rolePermissionMapping')
    op.drop_table('refreshTokens')
    op.drop_table('plan_features')
    op.drop_table('passwordResetTokens')
    op.drop_table('otpVerifications')
    op.drop_table('messages')
    op.drop_index('idx_media_files_uploaded_by', table_name='media_files')
    op.drop_index('idx_media_files_tenant_id', table_name='media_files')
    op.drop_index('idx_media_files_created_at', table_name='media_files')
    op.drop_table('media_files')
    op.drop_table('loginHistory')
    op.drop_table('guest_checkout_logs')
    op.drop_table('customerSessions')
    op.drop_table('customer_password_reset_tokens')
    op.drop_table('customer_notes')
    op.drop_table('customer_group_members')
    op.drop_table('customer_consent_logs')
    op.drop_table('customerAddresses')
    op.drop_table('customer_activity_logs')
    op.drop_index(op.f('ix_brandApprovals_requesting_store_id'), table_name='brandApprovals')
    op.drop_index(op.f('ix_brandApprovals_request_status'), table_name='brandApprovals')
    op.drop_index(op.f('ix_brandApprovals_brand_owner_store_id'), table_name='brandApprovals')
    op.drop_index(op.f('ix_brandApprovals_brand_id'), table_name='brandApprovals')
    op.drop_index(op.f('ix_brandApprovals_approval_end_date'), table_name='brandApprovals')
    op.drop_table('brandApprovals')
    op.drop_table('approval_request_versions')
    op.drop_table('users')
    op.drop_index('idx_tenant_city_state', table_name='tenants_details')
    op.drop_table('tenants_details')
    op.drop_table('tenantStatus')
    op.drop_index('uq_tags_platform_slug', table_name='tags', postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.drop_index('uq_tags_platform_name', table_name='tags', postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.drop_index('idx_tags_tenant_id', table_name='tags')
    op.drop_index('idx_tags_tag_type', table_name='tags')
    op.drop_index('idx_tags_store_id', table_name='tags')
    op.drop_index('idx_tags_is_system_tag', table_name='tags')
    op.drop_index('idx_tags_is_active', table_name='tags')
    op.drop_table('tags')
    op.drop_table('subscription_plans')
    op.drop_index(op.f('ix_statusHistory_entity_type'), table_name='statusHistory')
    op.drop_index(op.f('ix_statusHistory_entity_id'), table_name='statusHistory')
    op.drop_index(op.f('ix_statusHistory_changed_at'), table_name='statusHistory')
    op.drop_table('statusHistory')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_index(op.f('ix_entityVersions_entity_type'), table_name='entityVersions')
    op.drop_index(op.f('ix_entityVersions_entity_id'), table_name='entityVersions')
    op.drop_index(op.f('ix_entityVersions_created_at'), table_name='entityVersions')
    op.drop_table('entityVersions')
    op.drop_table('entity_verifications')
    op.drop_table('customers')
    op.drop_table('customer_groups')
    op.drop_table('conversations')
    op.drop_table('chatUsers')
    op.drop_index('uq_categories_platform_slug', table_name='categories', postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.drop_index('uq_categories_platform_name', table_name='categories', postgresql_where='store_id IS NULL AND deleted_at IS NULL')
    op.drop_index('idx_categories_tenant_id', table_name='categories')
    op.drop_index('idx_categories_store_id', table_name='categories')
    op.drop_index('idx_categories_parent_id', table_name='categories')
    op.drop_index('idx_categories_is_active', table_name='categories')
    op.drop_index('idx_categories_category_type', table_name='categories')
    op.drop_table('categories')
    op.drop_index(op.f('ix_brands_tenant_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_owner_store_id'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_platform_brand'), table_name='brands')
    op.drop_index(op.f('ix_brands_is_active'), table_name='brands')
    op.drop_index(op.f('ix_brands_brand_name'), table_name='brands')
    op.drop_table('brands')
    op.drop_index(op.f('ix_auditLogs_performed_by'), table_name='auditLogs')
    op.drop_index(op.f('ix_auditLogs_entity_type'), table_name='auditLogs')
    op.drop_index(op.f('ix_auditLogs_entity_id'), table_name='auditLogs')
    op.drop_index(op.f('ix_auditLogs_created_at'), table_name='auditLogs')
    op.drop_table('auditLogs')
    op.drop_index(op.f('ix_approvalRequests_tenant_id'), table_name='approvalRequests')
    op.drop_index(op.f('ix_approvalRequests_submitted_at'), table_name='approvalRequests')
    op.drop_index(op.f('ix_approvalRequests_entity_type'), table_name='approvalRequests')
    op.drop_index(op.f('ix_approvalRequests_entity_id'), table_name='approvalRequests')
    op.drop_index(op.f('ix_approvalRequests_approval_status'), table_name='approvalRequests')
    op.drop_table('approvalRequests')
    # ### end Alembic commands ###
