# Owner: mousamdas156@gmail.com
"""
================================================================================
SECTION ENDPOINTS ROUTER
================================================================================
Yeh file sections ke REST API endpoints (GET, POST, PATCH, DELETE) ko expose karti hai.
This module defines the routing layer for page Sections.

Why it is used:
- Maps incoming HTTP requests to corresponding backend service calls.
- Enforces payload validation and schema serialization.
================================================================================
"""

import uuid
from fastapi import APIRouter, Depends, Query, status
from sqlalchemy.ext.asyncio import AsyncSession

from app.db.session import getDb
from app.schemas.section import SectionCreate, SectionResponse, SectionUpdate
from app.services.sectionService import SectionService

# Initializing APIRouter with:
# - prefix="/sections": All routes inside will start with '/sections' (e.g. POST /sections/)
# - tags=["Sections"]: Grouping name in the autogenerated OpenAPI docs (/docs)
from app.core.rbac import Roles, require_role

router = APIRouter(prefix="/sections", tags=["Sections"])


@router.post(
    "/",
    response_model=SectionResponse,
    status_code=status.HTTP_201_CREATED,
    dependencies=[Depends(require_role(Roles.PLATFORM_OWNER, Roles.STORE_OWNER, Roles.STORE_ADMIN))],
)
async def createSection(
    data: SectionCreate,
    session: AsyncSession = Depends(getDb),
):
    """
    Creates a new Section block.
    """
    service = SectionService(session)
    return await service.createSection(data)


@router.get("/{sectionId}", response_model=SectionResponse)
async def getSection(
    sectionId: uuid.UUID,
    session: AsyncSession = Depends(getDb),
):
    """
    Gets details of a single section block using its unique UUID.
    """
    service = SectionService(session)
    return await service.getSection(sectionId)


@router.get("/", response_model=list[SectionResponse])
async def listSections(
    storeId: uuid.UUID = Query(..., description="Store UUID to filter sections for multi-tenant isolation"),
    session: AsyncSession = Depends(getDb),
):
    """
    Lists all section blocks for a specific store.
    """
    service = SectionService(session)
    return await service.listSections(storeId=storeId)


@router.patch(
    "/{sectionId}",
    response_model=SectionResponse,
    dependencies=[Depends(require_role(Roles.PLATFORM_OWNER, Roles.STORE_OWNER, Roles.STORE_ADMIN))],
)
async def updateSection(
    sectionId: uuid.UUID,
    data: SectionUpdate,
    session: AsyncSession = Depends(getDb),
):
    """
    Partially updates section configuration properties.
    """
    service = SectionService(session)
    return await service.updateSection(sectionId, data)


@router.delete(
    "/{sectionId}",
    status_code=status.HTTP_204_NO_CONTENT,
    dependencies=[Depends(require_role(Roles.PLATFORM_OWNER, Roles.STORE_OWNER))],
)
async def deleteSection(
    sectionId: uuid.UUID,
    session: AsyncSession = Depends(getDb),
):
    """
    Deletes a section block. Returns a 204 No Content response on successful deletion.
    """
    service = SectionService(session)
    await service.deleteSection(sectionId)

